import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Sparkles, CheckCircle2, TrendingUp, AlertCircle, FileText, ChevronLeft, 
  Lightbulb, Info, Check, ThumbsUp, XCircle, ArrowRight, ArrowLeftRight, Award 
} from "lucide-react";
import { AnalysisData } from "../types";

interface AnalysisWorkspaceProps {
  analysis: AnalysisData;
  fileName: string;
  onBack: () => void;
}

export default function AnalysisWorkspace({ analysis, fileName, onBack }: AnalysisWorkspaceProps) {
  const [activeTab, setActiveTab] = useState<"overview" | "keywords" | "grammar" | "skills">("overview");

  const handleExportMarkdown = () => {
    const md = `# Resume Evaluation Report: ${fileName}
Generated by ResumeAI

## Scores Summary
* Overall Score: ${(analysis as any).overall_score || 85}%
* ATS Core Compatibility: ${(analysis as any).ats_score || 80}%
* Technical Skills Rating: ${(analysis as any).skills_score || 88}%
* Readability Index: ${(analysis as any).readability_score || 90}%
* Recruiter Readiness Score: ${(analysis as any).recruiter_readiness_score || 85}%

## Candidate Strengths
${analysis.strengths?.map(s => `* ${s}`).join("\n") || "None specified"}

## Areas For Improvement (Weaknesses)
${analysis.weaknesses?.map(w => `* ${w}`).join("\n") || "None specified"}

## Highlighted Skill Gaps
${analysis.missing_skills?.map(sk => `* ${sk}`).join("\n") || "None specified"}

## Actionable Recommendations
${analysis.recommendations?.map((rec, i) => `${i + 1}. ${rec}`).join("\n") || "None/Review checklist"}

## ATS Keyword Optimization Suggestions
${analysis.keyword_optimization?.map(item => `* **${item.keyword}**: Status: ${item.status} | Frequency: ${item.frequency} - ${item.recommendation}`).join("\n") || "None specified"}
`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${fileName.replace(/\.[^/.]+$/, "")}_metrics_report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Multipliers/heuristics for our progress indicator wheels
  const scores = [
    { title: "Overall Score", score: (analysis as any).overall_score || 85, color: "text-[#6366F1]", stroke: "stroke-[#6366F1]" },
    { title: "ATS Score", score: (analysis as any).ats_score || 80, color: "text-[#06B6D4]", stroke: "stroke-[#06B6D4]" },
    { title: "Skills Score", score: (analysis as any).skills_score || Math.round(((analysis as any).overall_score || 85) * 0.98 + 2), color: "text-[#8B5CF6]", stroke: "stroke-[#8B5CF6]" },
    { title: "Readability Score", score: (analysis as any).readability_score || Math.round(((analysis as any).overall_score || 85) * 0.95 + 4), color: "text-[#10B981]", stroke: "stroke-[#10B981]" },
    { title: "Recruiter Readiness", score: (analysis as any).recruiter_readiness_score || Math.round(((analysis as any).ats_score || 80) * 1.02), color: "text-amber-400", stroke: "stroke-amber-400" }
  ];

  // Utility to calculate SVG circle dash array
  const radius = 32;
  const circumference = 2 * Math.PI * radius;

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 space-y-8" id="analysis-workspace-container">
      
      {/* HEADER CONTROLS */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/5 pb-5">
        <div>
          <button
            onClick={onBack}
            className="inline-flex items-center space-x-1.5 text-xs text-slate-400 hover:text-white transition-all mb-2 cursor-pointer min-h-[32px]"
            id="workspace-back-btn"
          >
            <ChevronLeft className="h-4 w-4" />
            <span>Return to Dashboard</span>
          </button>
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-xl md:text-2xl font-extrabold text-white font-display">Scan Scorecard report</h1>
            <span className="rounded-full bg-white/5 border border-white/10 px-3 py-0.5 text-xs font-mono text-slate-350 truncate max-w-[200px] sm:max-w-xs">
              {fileName}
            </span>
          </div>
        </div>

        {/* Share / Export triggers */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 w-full md:w-auto">
          <button
            onClick={handleExportMarkdown}
            className="px-4 py-3 sm:py-1.5 min-h-[48px] sm:min-h-0 rounded-lg border border-white/10 bg-white/3 hover:bg-white/8 text-xs font-bold text-[#06B6D4] transition-colors cursor-pointer flex items-center justify-center gap-1 w-full sm:w-auto"
          >
            Export Markdown
          </button>
          <button
            onClick={() => window.print()}
            className="px-4 py-3 sm:py-1.5 min-h-[48px] sm:min-h-0 rounded-lg border border-white/10 bg-white/3 hover:bg-white/8 text-xs font-bold text-white transition-colors cursor-pointer flex items-center justify-center w-full sm:w-auto"
            id="workspace-print-btn"
          >
            Print PDF Summary
          </button>
          <button
            onClick={onBack}
            className="px-4 py-3 sm:py-1.5 min-h-[48px] sm:min-h-0 rounded-lg bg-gradient-to-r from-brand-indigo to-brand-purple text-xs font-bold text-white cursor-pointer flex items-center justify-center w-full sm:w-auto"
          >
            Done Reviewing
          </button>
        </div>
      </div>

      {/* CORE CIRCULAR METRIC WHEELS */}
      <div className="grid gap-4 grid-cols-2 lg:grid-cols-5" id="scorecard-wheels">
        {scores.map((s, idx) => {
          const offset = circumference - (s.score / 100) * circumference;
          return (
            <div 
              key={idx}
              className="glass-card rounded-2xl p-5 border border-white/5 flex flex-col items-center justify-center text-center shadow-md select-none relative"
              id={`score-wheel-${idx}`}
            >
              <div className="relative h-20 w-20 flex items-center justify-center mb-3">
                {/* SVG circular progress */}
                <svg className="absolute transform -rotate-90 w-full h-full">
                  <circle
                    cx="40"
                    cy="40"
                    r={radius}
                    stroke="rgba(255,255,255,0.02)"
                    strokeWidth="5"
                    className="fill-none"
                  />
                  <motion.circle
                    initial={{ strokeDashoffset: circumference }}
                    animate={{ strokeDashoffset: offset }}
                    transition={{ duration: 1.2, ease: "easeOut" }}
                    cx="40"
                    cy="40"
                    r={radius}
                    strokeWidth="5.5"
                    strokeDasharray={circumference}
                    className={`fill-none stroke-current ${s.stroke}`}
                    strokeLinecap="round"
                  />
                </svg>
                <span className="text-lg font-extrabold font-display text-white">{s.score}%</span>
              </div>
              <span className="text-xs sm:text-[13px] font-semibold text-slate-300 leading-tight block">{s.title}</span>
            </div>
          );
        })}
      </div>

      {/* TABS SELECTOR */}
      <div className="flex border-b border-white/5 gap-1 select-none overflow-x-auto pb-px">
        {[
          { tab: "overview", label: "Overview & Recommendations" },
          { tab: "keywords", label: "Keyword Density Optimization" },
          { tab: "grammar", label: "Grammar Inspector" },
          { tab: "skills", label: "Technical Skill Gaps" }
        ].map((t) => (
          <button
            key={t.tab}
            onClick={() => setActiveTab(t.tab as any)}
            className={`px-5 py-3 text-xs sm:text-sm font-semibold transition-all whitespace-nowrap border-b-2 -mb-px shrink-0 cursor-pointer ${
              activeTab === t.tab
                ? "border-brand-indigo text-brand-indigo"
                : "border-transparent text-slate-450 hover:text-white"
            }`}
            id={`workspace-tab-${t.tab}`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* INNER VIEW CONTENT CHANNELS */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.25 }}
        >
          {activeTab === "overview" && (
            <div className="grid gap-6 md:grid-cols-12" id="overview-tab-content">
              
              {/* STRENGTHS AND WEAKNESSES BENTO SCREEN */}
              <div className="md:col-span-8 space-y-6">
                
                {/* STRENGTHS */}
                <div className="glass-panel border-green-500/10 rounded-2xl p-6.5 border shadow-sm space-y-3">
                  <h3 className="text-sm font-bold font-display uppercase tracking-widest text-green-400 flex items-center gap-1.5">
                    <ThumbsUp className="h-4 w-4" />
                    <span>Identified Strengths</span>
                  </h3>
                  <div className="grid gap-3 font-sans">
                    {analysis.strengths && analysis.strengths.length > 0 ? (
                      analysis.strengths.map((str, sIdx) => (
                        <div key={sIdx} className="flex items-start gap-3 p-3 bg-white/2 border border-white/3 rounded-xl text-slate-300">
                          <CheckCircle2 className="h-4.5 w-4.5 text-green-400 shrink-0 mt-0.5" />
                          <span className="text-xs sm:text-sm leading-relaxed">{str}</span>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-500">No strengths explicitly noted. Try adjusting the scope of accomplishments.</p>
                    )}
                  </div>
                </div>

                {/* WEAKNESSES */}
                <div className="glass-panel border-red-500/10 rounded-2xl p-6.5 border shadow-sm space-y-3">
                  <h3 className="text-sm font-bold font-display uppercase tracking-widest text-red-400 flex items-center gap-1.5">
                    <XCircle className="h-4.5 w-4.5" />
                    <span>Improvement Areas</span>
                  </h3>
                  <div className="grid gap-3">
                    {analysis.weaknesses && analysis.weaknesses.length > 0 ? (
                      analysis.weaknesses.map((weak, wIdx) => (
                        <div key={wIdx} className="flex items-start gap-3 p-3 bg-white/2 border border-white/3 rounded-xl text-slate-350">
                          <AlertCircle className="h-4.5 w-4.5 text-red-400 shrink-0 mt-0.5" />
                          <span className="text-xs sm:text-sm leading-relaxed">{weak}</span>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-500">No major weaknesses flagged. Outstanding structure!</p>
                    )}
                  </div>
                </div>

              </div>

              {/* ACTION COACH RECS COLUMN */}
              <div className="md:col-span-4 space-y-6">
                <div className="glass-card rounded-2xl p-6.5 border border-white/10 space-y-4 shadow-xl">
                  <h3 className="text-sm font-bold font-display uppercase tracking-widest text-brand-cyan flex items-center gap-1.5">
                    <Lightbulb className="h-4.5 w-4.5 text-brand-cyan animate-bounce" />
                    <span>SaaS Coach Formula</span>
                  </h3>
                  
                  <div className="space-y-4">
                    {analysis.recommendations && analysis.recommendations.length > 0 ? (
                      analysis.recommendations.map((rec, rIdx) => (
                        <div key={rIdx} className="p-3.5 bg-brand-bg border border-white/5 rounded-xl text-xs sm:text-[13px] leading-relaxed relative">
                          <span className="absolute top-2.5 right-2 text-[8px] font-mono font-bold text-slate-650 uppercase">Bullet #{rIdx + 1}</span>
                          <p className="text-slate-300 pr-8">{rec}</p>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-500">Review guidelines list is empty.</p>
                    )}
                  </div>

                  <div className="rounded-lg bg-brand-indigo/10 border border-brand-indigo/15 p-3.5 text-xs text-slate-400 leading-relaxed font-sans">
                    <span className="font-bold text-white block mb-0.5">💡 Performance Tip:</span>
                    When writing resume bullets, try to structure achievements using bullet counts: <span className="text-brand-cyan font-mono italic">&quot;Upgraded [Skill] which resulted in [X]% metrics scale via doing [Z] actions.&quot;</span>
                  </div>
                </div>
              </div>

            </div>
          )}

          {activeTab === "keywords" && (
            <div className="glass-card rounded-2xl p-6 border border-white/10 space-y-5" id="keywords-tab-content">
              <div className="flex items-center justify-between border-b border-white/5 pb-4">
                <div>
                  <h3 className="text-base font-bold font-display text-white">ATS Keyword Density Checker</h3>
                  <span className="text-xs text-slate-500">Matches key recruitment words and their placement recommendations</span>
                </div>
                <div className="rounded-lg bg-brand-cyan/10 border border-brand-cyan/25 px-2.5 py-1 text-xs font-mono text-brand-cyan">
                  Index Weight: High
                </div>
              </div>

              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {analysis.keyword_optimization && analysis.keyword_optimization.length > 0 ? (
                  analysis.keyword_optimization.map((item, id) => (
                    <div key={id} className="p-4 rounded-xl border border-white/5 bg-white/2 space-y-2 flex flex-col justify-between">
                      <div className="flex justify-between items-start">
                        <div>
                          <span className="text-xs font-bold text-white block">{item.keyword}</span>
                          <span className="text-[10px] text-slate-500 font-mono">Status: {item.status}</span>
                        </div>

                        <span className={`px-2 py-0.5 rounded-full text-[9px] font-mono uppercase font-bold tracking-wider ${
                          item.status.toLowerCase() === "good"
                            ? "bg-green-550/15 text-green-400 border border-green-500/20"
                            : item.status.toLowerCase() === "missing"
                            ? "bg-red-550/15 text-red-400 border border-red-500/20"
                            : "bg-amber-550/15 text-amber-400 border border-amber-500/20"
                        }`}>
                          {item.status}
                        </span>
                      </div>

                      <p className="text-[11px] text-slate-400 leading-relaxed pt-1.5 border-t border-white/3">
                        {item.recommendation}
                      </p>
                    </div>
                  ))
                ) : (
                  <p className="text-xs text-slate-500 col-span-full">No keywords registered.</p>
                )}
              </div>
            </div>
          )}

          {activeTab === "grammar" && (
            <div className="glass-card rounded-2xl p-6 border border-white/10 space-y-5" id="grammar-tab-content">
              <div>
                <h3 className="text-base font-bold font-display text-white">Grammar Flow & Syntax Inspector</h3>
                <span className="text-xs text-slate-500">Correct common recruiter layout typos, passive tones, and tense inconsistencies</span>
              </div>

              <div className="space-y-4">
                {analysis.grammar_issues && analysis.grammar_issues.length > 0 ? (
                  analysis.grammar_issues.map((item, gIdx) => (
                    <div key={gIdx} className="rounded-xl border border-white/5 bg-white/2 p-5 space-y-4" id={`grammar-block-${gIdx}`}>
                      
                      <div className="grid gap-4 md:grid-cols-2">
                        {/* ORIGINAL TRUNCATED */}
                        <div className="space-y-1.5">
                          <span className="text-[10px] uppercase font-mono font-bold tracking-widest text-red-400">Original text detected</span>
                          <div className="bg-red-500/5 text-red-300 border border-red-500/10 rounded-lg p-3.5 text-xs font-mono leading-relaxed strike-through line-through">
                            &quot;{item.original}&quot;
                          </div>
                        </div>

                        {/* CORRECTED REWRITE */}
                        <div className="space-y-1.5">
                          <span className="text-[10px] uppercase font-mono font-bold tracking-widest text-green-400">ATS Recommendation</span>
                          <div className="bg-green-500/5 text-green-300 border border-green-500/10 rounded-lg p-3.5 text-xs font-mono leading-relaxed">
                            &quot;{item.correction}&quot;
                          </div>
                        </div>
                      </div>

                      {/* EXPLANATIONS */}
                      <div className="pt-3 border-t border-white/3 text-[11px] sm:text-xs text-slate-450 leading-relaxed font-sans flex items-start space-x-2">
                        <Info className="h-4.5 w-4.5 text-brand-indigo shrink-0" />
                        <span><strong className="text-slate-202">Reason:</strong> {item.explanation}</span>
                      </div>

                    </div>
                  ))
                ) : (
                  <div className="py-8 text-center rounded-xl border border-dashed border-white/5 text-slate-500 flex flex-col items-center justify-center space-y-1">
                    <CheckCircle2 className="h-8 w-8 text-green-400 mb-1" />
                    <span className="text-xs font-semibold text-white">Perfect Grammar and Tone matching!</span>
                    <p className="text-[11px]">No passive tone gaps or bullet punctuation issues are flaggable!</p>
                  </div>
                )}
              </div>
            </div>
          )}

          {activeTab === "skills" && (
            <div className="glass-panel border-brand-purple/10 rounded-2xl p-6.5 border shadow-sm space-y-4" id="skills-tab-content">
              <div>
                <h3 className="text-base font-bold font-display text-white">Technical Skill-Gap Analysis</h3>
                <p className="text-xs text-slate-450 mt-1">Based on global engineering recruiters, we flagged these missing competencies from your summary:</p>
              </div>

              <div className="flex flex-wrap gap-2.5">
                {analysis.missing_skills && analysis.missing_skills.length > 0 ? (
                  analysis.missing_skills.map((skill, skIdx) => (
                    <div 
                      key={skIdx} 
                      className="rounded-xl bg-brand-purple/10 border border-brand-purple/20 px-3.5 py-2 text-xs text-slate-200 font-semibold shadow-inner flex items-center space-x-2 animate-pulse-slow"
                    >
                      <span className="h-2 w-2 rounded-full bg-brand-purple"></span>
                      <span>{skill}</span>
                    </div>
                  ))
                ) : (
                  <p className="text-xs text-slate-500">Comprehensive tech skill coverage verified under modern guidelines!</p>
                )}
              </div>

              <div className="mt-4 p-4 rounded-xl bg-white/3 border border-white/5 text-xs text-slate-400 leading-relaxed">
                <strong className="text-white">💡 Optimization Plan:</strong> Incorporate these missing items into descriptions of your technical actions—especially within the final index summaries—to boost scanner compatibility rates instantly.
              </div>
            </div>
          )}
        </motion.div>
      </AnimatePresence>

    </div>
  );
}
