import React, { useState } from "react";
import { motion } from "motion/react";
import { 
  Sparkles, Compass, CheckCircle2, ChevronRight, RefreshCw, 
  BookOpen, Terminal, Award, FileText, Download, Target 
} from "lucide-react";
import { CareerRoadmapData } from "../types";

interface CareerRoadmapToolProps {
  onGenerateRoadmap: (skills: string, role: string) => Promise<CareerRoadmapData>;
}

export default function CareerRoadmapTool({ onGenerateRoadmap }: CareerRoadmapToolProps) {
  const [currentSkills, setCurrentSkills] = useState("React, JavaScript, Basic CSS");
  const [targetRole, setTargetRole] = useState("Senior Fullstack Developer");
  const [loading, setLoading] = useState(false);
  const [roadmap, setRoadmap] = useState<CareerRoadmapData | null>(null);
  const [errorMsg, setErrorMsg] = useState("");

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentSkills.trim() || !targetRole.trim()) {
      setErrorMsg("Please provide both your current skills and target career role.");
      return;
    }

    setErrorMsg("");
    setLoading(true);
    try {
      const generated = await onGenerateRoadmap(currentSkills, targetRole);
      setRoadmap(generated);
    } catch (err: any) {
      setErrorMsg("Failed to synthesize career roadmap: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  const loadPreset = (presetSkills: string, presetRole: string) => {
    setCurrentSkills(presetSkills);
    setTargetRole(presetRole);
  };

  const handleExportMarkdown = () => {
    if (!roadmap) return;
    const md = `# AI Career Roadmap: Transition from ${currentSkills} to ${targetRole}
Generated by ResumeAI

## 30-Day Foundation Phase
${roadmap.timeline.plan_30_day.map((item, i) => `${i + 1}. ${item}`).join("\n")}

## 90-Day Execution Phase
${roadmap.timeline.plan_90_day.map((item, i) => `${i + 1}. ${item}`).join("\n")}

## 6-Month Mastery Phase (180-Day)
${roadmap.timeline.plan_180_day.map((item, i) => `${i + 1}. ${item}`).join("\n")}

## Recommended Practice Projects
${roadmap.recommendations.projects.map(p => `### ${p.name}\n${p.description}`).join("\n\n")}

## Educational Courses
${roadmap.recommendations.courses.map(c => `* ${c.name} (${c.platform})`).join("\n")}

## Learning Resources
${roadmap.recommendations.resources.map(r => `* ${r}`).join("\n")}
`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${targetRole.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_roadmap.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 space-y-8 animate-fade-in" id="roadmap-wrapper">
      
      {/* Header Info */}
      <div className="border-b border-white/5 pb-5">
        <div className="flex items-center space-x-1 border border-[#8B5CF6]/30 bg-[#8B5CF6]/10 rounded-full w-fit px-3 py-1 font-mono text-[10px] uppercase font-bold tracking-wider text-purple-400 mb-3">
          <Sparkles className="h-3 w-3 text-purple-400" />
          <span>Frictionless Path Builder</span>
        </div>
        <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-black text-white font-display flex items-center space-x-2.5 tracking-tight">
          <Compass className="h-7 w-7 text-[#8B5CF6] animate-pulse shrink-0" />
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-white via-slate-100 to-slate-400">AI Career Roadmap Generator</span>
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1 max-w-3xl">
          Transform your current skills into a tailored timeline plan for transitioning successfully to your target role. Evaluates skill gaps and suggests real-world courses & learning timelines.
        </p>
      </div>

      <div className="grid gap-8 lg:grid-cols-12">
        {/* Input Parameters Box */}
        <div className="lg:col-span-5">
          <form onSubmit={handleGenerate} className="glass-card rounded-2xl p-6 border border-white/10 space-y-5 shadow-2xl relative">
            <div className="absolute top-0 right-0 transform translate-x-2 -translate-y-2 select-none">
              <span className="bg-[#8B5CF6]/10 border border-[#8B5CF6]/30 rounded px-2 py-0.5 text-[8px] font-mono text-[#8B5CF6] font-bold uppercase tracking-widest">
                AI Agent Enabled
              </span>
            </div>

            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest">Current Skill set</label>
                <div className="flex space-x-2 select-none">
                  <button 
                    type="button" 
                    onClick={() => loadPreset("Python, SQL, Analytics", "AI Engineer")}
                    className="text-[10px] text-brand-cyan hover:underline transition-all"
                  >
                    Preset AI
                  </button>
                  <button 
                    type="button" 
                    onClick={() => loadPreset("HTML, Simple CSS, Figma", "Senior UI Designer")}
                    className="text-[10px] text-brand-cyan hover:underline transition-all"
                  >
                    Preset Core UI
                  </button>
                </div>
              </div>
              <textarea
                value={currentSkills}
                onChange={(e) => setCurrentSkills(e.target.value)}
                placeholder="List your core active programming skills or current technologies (e.g., Python, SQL, Git, Excel)..."
                required
                className="w-full glass-input rounded-xl p-4 text-xs h-28 font-sans leading-relaxed resize-none"
                id="roadmap-skills"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest">Target Role Goal</label>
              <input
                type="text"
                value={targetRole}
                onChange={(e) => setTargetRole(e.target.value)}
                placeholder="e.g. Machine Learning Engineer or Solutions Architect"
                required
                className="w-full glass-input rounded-xl px-4 py-3 text-xs font-sans font-medium"
                id="roadmap-target-role"
              />
            </div>

            {errorMsg && (
              <div className="rounded-lg bg-red-400/10 border border-red-500/25 p-3.5 text-xs text-red-400 flex items-start space-x-2">
                <span>⚠️ {errorMsg}</span>
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3.5 px-4 min-h-[48px] rounded-xl bg-gradient-to-r from-[#6366F1] via-[#8B5CF6] to-[#06B6D4] hover:brightness-110 font-bold text-xs sm:text-sm text-white shadow-lg flex items-center justify-center space-x-2 transition-all active:scale-95 disabled:opacity-50 cursor-pointer"
              id="roadmap-submit-btn"
            >
              {loading ? (
                <>
                  <RefreshCw className="h-4.5 w-4.5 animate-spin" />
                  <span>Structuring Career Milestones...</span>
                </>
              ) : (
                <>
                  <span>Construct Career Roadmap</span>
                  <ChevronRight className="h-4 w-4" />
                </>
              )}
            </button>
          </form>

          {/* Tips card */}
          <div className="mt-6 p-5 glass-panel rounded-2xl border border-white/5 text-xs leading-relaxed text-slate-400 space-y-2 shadow-sm">
            <span className="font-bold text-slate-200 block">💡 Learning Concept:</span>
            <p>
              ResumeAI uses Gemini 2.5 Flash API models to construct the ideal logical sequence to guide your professional milestones. Review modern certifications, structure dual practice repositories, and validate critical competencies to maximize recruiter outlook metrics fast.
            </p>
          </div>
        </div>

        {/* Output Roadmap Timeline & Recommendations view */}
        <div className="lg:col-span-7">
          {roadmap ? (
            <div className="space-y-8 animate-fade-in" id="roadmap-results-area">
              
              {/* Toolbar */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white/3 border border-white/10 p-3 rounded-xl select-none">
                <span className="text-xs text-emerald-400 font-mono font-bold flex items-center gap-1.5 justify-center sm:justify-start">
                  <span className="relative flex h-2 w-2">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                  </span>
                  Transition Roadmap Ready
                </span>
                <div className="flex space-x-2 w-full sm:w-auto">
                  <button
                    onClick={handleExportMarkdown}
                    className="flex-1 sm:flex-none p-2 sm:p-1 px-3 min-h-[40px] sm:min-h-0 border border-white/10 bg-white/3 hover:bg-white/8 rounded-lg text-xs font-semibold text-white transition-all flex items-center justify-center space-x-1 cursor-pointer"
                    id="export-roadmap-btn"
                  >
                    <Download className="h-3.5 w-3.5 text-brand-cyan" />
                    <span>Download MD</span>
                  </button>
                  <button
                    onClick={() => window.print()}
                    className="flex-1 sm:flex-none p-2 sm:p-1.5 px-3 min-h-[40px] sm:min-h-0 rounded-lg bg-gradient-to-r from-brand-indigo to-brand-purple text-xs font-bold text-white flex items-center justify-center space-x-1 cursor-pointer"
                  >
                    <FileText className="h-3.5 w-3.5" />
                    <span>Print PDF Summary</span>
                  </button>
                </div>
              </div>

              {/* TIMELINE TRACK */}
              <div className="glass-panel p-6.5 rounded-2xl border border-white/10 space-y-6 relative overflow-hidden shadow-xl">
                <div className="border-b border-white/5 pb-4 mb-4">
                  <span className="text-xs uppercase font-mono tracking-widest font-bold text-[#8B5CF6]">Transition Progression Path</span>
                  <h3 className="text-lg font-bold font-display text-white mt-1">30, 90, & 180 Day Sequential Phases</h3>
                </div>

                <div className="space-y-8 relative before:absolute before:left-4 before:top-2 before:bottom-2 before:w-0.5 before:bg-white/10">
                  {/* PHASE 30 DAY */}
                  <div className="relative pl-10 group">
                    <div className="absolute left-1.5 top-1 h-5 w-5 rounded-full border-2 border-[#6366F1] bg-[#050816] flex items-center justify-center font-mono text-[9px] font-bold text-[#6366F1] shadow shadow-[#6366F1]/30">
                      1
                    </div>
                    <div className="space-y-1.5">
                      <div className="flex items-center space-x-2">
                        <span className="text-xs uppercase font-mono font-bold text-[#6366F1] tracking-wider">Days 1 - 30</span>
                        <span className="text-white font-semibold text-sm">Foundation & Core Concepts</span>
                      </div>
                      <ul className="grid gap-2 text-xs sm:text-[13px] text-slate-300 font-sans leading-relaxed">
                        {roadmap.timeline.plan_30_day.map((step, idx) => (
                          <li key={idx} className="flex items-start gap-2 bg-white/2 border border-white/3 rounded-lg p-2">
                            <CheckCircle2 className="h-4 w-4 text-indigo-400 mt-0.5 shrink-0" />
                            <span>{step}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* PHASE 90 DAY */}
                  <div className="relative pl-10 group animate-fade-in">
                    <div className="absolute left-1.5 top-1 h-5 w-5 rounded-full border-2 border-[#8B5CF6] bg-[#050816] flex items-center justify-center font-mono text-[9px] font-bold text-[#8B5CF6] shadow shadow-[#8B5CF6]/30">
                      2
                    </div>
                    <div className="space-y-1.5">
                      <div className="flex items-center space-x-2">
                        <span className="text-xs uppercase font-mono font-bold text-[#8B5CF6] tracking-wider">Days 31 - 90</span>
                        <span className="text-white font-semibold text-sm">Practical Applications & Portfolio</span>
                      </div>
                      <ul className="grid gap-2 text-xs sm:text-[13px] text-slate-300 font-sans leading-relaxed">
                        {roadmap.timeline.plan_90_day.map((step, idx) => (
                          <li key={idx} className="flex items-start gap-2 bg-white/2 border border-white/3 rounded-lg p-2">
                            <CheckCircle2 className="h-4 w-4 text-purple-400 mt-0.5 shrink-0" />
                            <span>{step}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* PHASE 180 DAY */}
                  <div className="relative pl-10 group">
                    <div className="absolute left-1.5 top-1 h-5 w-5 rounded-full border-2 border-[#06B6D4] bg-[#050816] flex items-center justify-center font-mono text-[9px] font-bold text-[#06B6D4] shadow shadow-[#06B6D4]/30">
                      3
                    </div>
                    <div className="space-y-1.5">
                      <div className="flex items-center space-x-2">
                        <span className="text-xs uppercase font-mono font-bold text-[#06B6D4] tracking-wider">Days 91 - 180</span>
                        <span className="text-white font-semibold text-sm">Expertise Scale & System Authority</span>
                      </div>
                      <ul className="grid gap-2 text-xs sm:text-[13px] text-slate-300 font-sans leading-relaxed">
                        {roadmap.timeline.plan_180_day.map((step, idx) => (
                          <li key={idx} className="flex items-start gap-2 bg-white/2 border border-white/3 rounded-lg p-2">
                            <CheckCircle2 className="h-4 w-4 text-[#06B6D4] mt-0.5 shrink-0" />
                            <span>{step}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              {/* RECOMMENDED PROJECTS */}
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="glass-panel p-5 rounded-2xl border border-white/10 space-y-3">
                  <div className="flex items-center space-x-1.5 border-b border-white/5 pb-2 text-white">
                    <Terminal className="h-4.5 w-4.5 text-brand-cyan" />
                    <span className="font-display font-bold text-xs uppercase tracking-widest text-[#06B6D4]">Practice Projects</span>
                  </div>
                  <div className="space-y-3.5">
                    {roadmap.recommendations.projects.map((proj, pIdx) => (
                      <div key={pIdx} className="space-y-1">
                        <strong className="text-slate-100 text-xs sm:text-sm font-semibold">{proj.name}</strong>
                        <p className="text-[11px] text-slate-400 leading-relaxed font-sans">{proj.description}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* COURSES & RESOURCES */}
                <div className="glass-panel p-5 rounded-2xl border border-white/10 space-y-3">
                  <div className="flex items-center space-x-1.5 border-b border-white/5 pb-2 text-white">
                    <BookOpen className="h-4.5 w-4.5 text-[#8B5CF6]" />
                    <span className="font-display font-bold text-xs uppercase tracking-widest text-brand-purple">Courses & Resources</span>
                  </div>
                  
                  <div className="space-y-3">
                    <div className="space-y-1.5">
                      <span className="text-[10px] uppercase font-mono font-bold text-slate-500">Recommended Courses</span>
                      {roadmap.recommendations.courses.map((course, cIdx) => (
                        <div key={cIdx} className="text-xs bg-white/2 p-2 border border-white/3 rounded-lg text-slate-300 flex justify-between items-center pr-3">
                          <span className="truncate pr-2 font-medium">{course.name}</span>
                          <span className="text-[9px] bg-indigo-500/10 border border-indigo-500/20 rounded px-1.5 py-0.5 font-mono text-indigo-400 capitalize whitespace-nowrap">{course.platform}</span>
                        </div>
                      ))}
                    </div>

                    <div className="space-y-1.5 pt-1.5 border-t border-white/5">
                      <span className="text-[10px] uppercase font-mono font-bold text-slate-500">Reference Resources</span>
                      <ul className="text-xs text-slate-400 space-y-1 list-disc pl-4 font-medium">
                        {roadmap.recommendations.resources.map((res, rIdx) => (
                          <li key={rIdx}>{res}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          ) : (
            /* EMPTY VIEW waiting on parameters */
            <div className="h-full min-h-[400px] flex flex-col items-center justify-center border border-dashed border-white/5 rounded-2xl bg-[#050816]/30 text-slate-500 text-center px-6 shadow-sm">
              <Compass className="h-12 w-12 text-slate-600 mb-3 animate-spin-slow" />
              <h3 className="text-base font-bold text-white font-display mb-1">Interactive Learning Track</h3>
              <p className="text-xs max-w-sm">
                Discuss your active baseline technologies on the configurator form, outline your target role objectives, and click construct career roadmap parameters.
              </p>
            </div>
          )}
        </div>
      </div>

    </div>
  );
}
